import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Quote from '../components/Quote';
import Wrapper from '../components/Wrapper';
import Nav from './Nav';



// const colors = chroma.scale(['#FF5F5D','#121212']).mode('lch').colors(10);

export default function MainSection() {
  return (
    <Wrapper>
      <div className={styles.container} style={{ backgroundColor: '#121212'}}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Quote color={'#121212'} />
        </main>

      </div>
    </Wrapper>
  )
}