import Head from 'next/head'
import Image from 'next/image'
import chroma from'chroma-js'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

const colors = chroma.scale(['#fafa6e','#2A4858']).mode('lch').colors(10);
const getRandomColor = () => colors[Math.floor(Math.random() * 10)];

export default function Home({ c }) {
  const [color, setColor] = useState(getRandomColor)
  const q = "Vorrei svolgerlo senza sentir l'obbligo di mandare in pezzi la mia vita in caso di una pausa."
  return (
    <div className={styles.container} style={{ backgroundColor: color}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => setColor(getRandomColor())}>Randomize</button>
        <div className={styles.quote}>
          <h1 className={styles.title}>
            Odio il lavoro perchè:
          </h1>
          <h2 className={styles.subtitle}>
            {q}
          </h2>
        </div>
      </main>

    </div>
  )
}

// export async function getStaticProps(context) {
//   return {
//     props: { c: getRandomColor() }, // will be passed to the page component as props
//   }
// }

// export async function getStaticPaths() {
//   return {
//     paths: [
//       // String variant:
//       '/',
//       '/[id]',
//       // Object variant:
//       // { params: { id: false } },
//     ],
//     fallback: true,
//   }
// }