import Head from 'next/head'
import Image from 'next/image'
import chroma from'chroma-js'
import { useState } from 'react';
import Papa from 'papaparse';
import styles from '../styles/Home.module.css'
import Quote from '../components/Quote';
import Nav from '../components/Nav';

const colors = chroma.scale(['#FF5F5D','#121212']).mode('lch').colors(10);
const getRandomColor = () => colors[Math.floor(Math.random() * 10)];

export default function Home({ c }) {
  const [color, setColor] = useState(getRandomColor)
  const q = "Vorrei svolgerlo senza sentir l'obbligo di mandare in pezzi la mia vita in caso di una pausa."
  // const p = Papa.parse('/public/entries', { delimiter: ",", complete: (s) => console.log(s)})
  // console.log(p)

  // fetch('/entries.csv')
  //   .then((r) => r.text())
  //   .then((r) => {
  //     const { data } = Papa.parse(r)
  //     // console.log(p)
  //     const formatted = data.map((item) => ({
  //       [data[0][0]]: item[0],
  //       [data[0][1]]: item[1],
  //       [data[0][2]]: item[2],
  //     }))
  //     formatted.shift()
  //     console.log(formatted)
  //   })

  return (
    <div className={styles.container} style={{ backgroundColor: '#121212'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className={styles.main}>
        <Quote color={color} onRefresh={() => setColor(getRandomColor())} />
      </main>

    </div>
  )
}

// export async function getStaticProps(context) {
//   return {
//     props: { c: getRandomColor() }, // will be passed to the page component as props
//   }
// }

// export async function getStaticPaths() {
//   return {
//     paths: [
//       // String variant:
//       '/',
//       '/[id]',
//       // Object variant:
//       // { params: { id: false } },
//     ],
//     fallback: true,
//   }
// }